--- THE SAMPLE CODE IS FOR NON-PRODUCTION USAGE ONLY
--- PROVIDED “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING 
--- THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
--- IN NO EVENT SHALL SENDER/CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
--- OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
--- LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) SUSTAINED BY YOU OR A THIRD PARTY, 
--- HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT ARISING 
--- IN ANY WAY OUT OF THE USE OF THIS SAMPLE CODE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----
--- to verify ghost records thread is running/progressing
--- fields to check from time to time: cpu-time, reads, writes, logical_reads, --> wait and blocking
SELECT * INTO #myexecrequests FROM sys.dm_exec_requests WHERE 1 = 0;
SET NOCOUNT ON;
DECLARE @a INT
SELECT @a = 0;
WHILE (@a < 1)
BEGIN
    INSERT INTO #myexecrequests SELECT * FROM sys.dm_exec_requests WHERE command LIKE '%ghost%'
    SELECT @a = COUNT (*) FROM #myexecrequests
END;
SELECT * FROM #myexecrequests;
DROP TABLE #myexecrequests;
